"""Build connector-safe authoring design guidance from agent-skills source."""

from __future__ import annotations

import hashlib
import json
import re
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SKILLS_ROOT = ROOT / "agent-skills"
DESIGN_SOURCE_PATH = SKILLS_ROOT / "smeme-decision-tree-author" / "DESIGN.md"
GENERATED_PATH = Path(__file__).resolve().parent / "_generated_design_guidance.py"

DESIGN_GUIDANCE_CONTENT_VERSION = "1.1.0"

_FRONTMATTER_RE = re.compile(r"\A---\s*\n.*?\n---\s*\n", re.DOTALL)

_BLIND_PROTOCOL_DENYLIST = (
    "graph_data",
    "edge_id",
    "compiled_theory",
)
_UUID_RE = re.compile(
    r"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}",
    re.IGNORECASE,
)


def strip_yaml_frontmatter(text: str) -> str:
    """Remove leading YAML frontmatter block if present."""
    return _FRONTMATTER_RE.sub("", text, count=1)


def normalize_design_body(text: str) -> str:
    """NFC-normalize and strip trailing whitespace per line."""
    normalized = unicodedata.normalize("NFC", text)
    lines = [line.rstrip() for line in normalized.splitlines()]
    return "\n".join(lines).strip()


def load_design_source(design_path: Path | None = None) -> str:
    """Read and normalize the design guidance source file."""
    path = design_path or DESIGN_SOURCE_PATH
    if not path.is_file():
        msg = f"missing authoring design guidance source: {path}"
        raise FileNotFoundError(msg)
    raw = path.read_text(encoding="utf-8")
    if not raw.strip():
        msg = f"empty authoring design guidance source: {path}"
        raise ValueError(msg)
    return normalize_design_body(strip_yaml_frontmatter(raw))


def design_content_digest(body: str) -> str:
    """SHA-256 digest prefixed with ``sha256:`` over canonical UTF-8 body."""
    payload = body.encode("utf-8")
    return f"sha256:{hashlib.sha256(payload).hexdigest()}"


def build_design_guidance_artifact(
    *,
    design_path: Path | None = None,
    content_version: str = DESIGN_GUIDANCE_CONTENT_VERSION,
) -> tuple[str, str, str]:
    """Return (version, digest, markdown) for the design guidance artifact."""
    body = load_design_source(design_path=design_path)
    digest = design_content_digest(body)
    return content_version, digest, body


def render_generated_module(
    *,
    content_version: str,
    content_digest: str,
    content_markdown: str,
) -> str:
    """Python module source for ``smeme/mcp/_generated_design_guidance.py``."""
    return (
        '"""Generated by scripts/build_design_guidance_artifact.py — do not edit by hand."""\n\n'
        "from __future__ import annotations\n\n"
        f'DESIGN_GUIDANCE_VERSION = "{content_version}"\n'
        f'DESIGN_GUIDANCE_DIGEST = "{content_digest}"\n'
        f"DESIGN_GUIDANCE_MARKDOWN = {json.dumps(content_markdown)}\n"
    )


def write_generated_module(
    path: Path | None = None,
    *,
    design_path: Path | None = None,
    content_version: str = DESIGN_GUIDANCE_CONTENT_VERSION,
) -> Path:
    """Build and write the committed design guidance artifact module."""
    version, digest, markdown = build_design_guidance_artifact(
        design_path=design_path,
        content_version=content_version,
    )
    out = path or GENERATED_PATH
    out.write_text(
        render_generated_module(
            content_version=version,
            content_digest=digest,
            content_markdown=markdown,
        ),
        encoding="utf-8",
    )
    return out


def assert_blind_protocol_safe(markdown: str) -> None:
    """Raise ValueError if design guidance leaks denylisted fields or UUIDs."""
    lower = markdown.lower()
    for token in _BLIND_PROTOCOL_DENYLIST:
        if token in lower:
            msg = f"design guidance markdown contains denylisted token: {token}"
            raise ValueError(msg)
    if _UUID_RE.search(markdown):
        raise ValueError("design guidance markdown contains workflow UUID pattern")
