"""Add workflow versioning to InProgressQNRGeneration

Revision ID: 4c3c382470ce
Revises: feaedf1f418c
Create Date: 2026-01-29 11:38:56.730266

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "4c3c382470ce"
down_revision: Union[str, None] = "feaedf1f418c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add workflow_version with server default for existing rows
    op.add_column(
        "in_progress_qnr_generations",
        sa.Column(
            "workflow_version",
            sqlmodel.sql.sqltypes.AutoString(length=50),
            nullable=False,
            server_default="1.0.0",
        ),
    )
    op.add_column(
        "in_progress_qnr_generations",
        sa.Column("workflow_updated_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("in_progress_qnr_generations", "workflow_updated_at")
    op.drop_column("in_progress_qnr_generations", "workflow_version")
    # ### end Alembic commands ###
