"""Initial schema

Revision ID: 9601d90d2008
Revises:
Create Date: 2025-12-17 20:55:54.433383

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "9601d90d2008"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "qnrs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("graph_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_public", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("was_ever_public", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("parent_qnr_id", sa.Uuid(), nullable=True),
        sa.Column("is_current", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("is_archived", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], name=op.f("fk_qnrs_author_id_users")),
        sa.ForeignKeyConstraint(
            ["parent_qnr_id"], ["qnrs.id"], name=op.f("fk_qnrs_parent_qnr_id_qnrs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_qnrs")),
    )
    op.create_index(op.f("ix_qnrs_is_archived"), "qnrs", ["is_archived"], unique=False)
    op.create_index(op.f("ix_qnrs_is_current"), "qnrs", ["is_current"], unique=False)
    op.create_index(op.f("ix_qnrs_is_public"), "qnrs", ["is_public"], unique=False)
    op.create_index(op.f("ix_qnrs_title"), "qnrs", ["title"], unique=False)
    op.create_index(op.f("ix_qnrs_was_ever_public"), "qnrs", ["was_ever_public"], unique=False)
    op.create_table(
        "qnr_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("qnr_id", sa.Uuid(), nullable=False),
        sa.Column("current_node_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("user_responses", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("conclusion_reached", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(["qnr_id"], ["qnrs.id"], name=op.f("fk_qnr_sessions_qnr_id_qnrs")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_qnr_sessions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_qnr_sessions")),
    )
    op.create_index(op.f("ix_qnr_sessions_qnr_id"), "qnr_sessions", ["qnr_id"], unique=False)
    op.create_index(op.f("ix_qnr_sessions_user_id"), "qnr_sessions", ["user_id"], unique=False)
    op.create_table(
        "memos",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("recommendations", sa.Text(), nullable=False),
        sa.Column(
            "llm_response",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["qnr_sessions.id"], name=op.f("fk_memos_session_id_qnr_sessions")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_memos_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memos")),
    )
    op.create_index(op.f("ix_memos_session_id"), "memos", ["session_id"], unique=False)
    op.create_index(op.f("ix_memos_user_id"), "memos", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_memos_user_id"), table_name="memos")
    op.drop_index(op.f("ix_memos_session_id"), table_name="memos")
    op.drop_table("memos")
    op.drop_index(op.f("ix_qnr_sessions_user_id"), table_name="qnr_sessions")
    op.drop_index(op.f("ix_qnr_sessions_qnr_id"), table_name="qnr_sessions")
    op.drop_table("qnr_sessions")
    op.drop_index(op.f("ix_qnrs_was_ever_public"), table_name="qnrs")
    op.drop_index(op.f("ix_qnrs_title"), table_name="qnrs")
    op.drop_index(op.f("ix_qnrs_is_public"), table_name="qnrs")
    op.drop_index(op.f("ix_qnrs_is_current"), table_name="qnrs")
    op.drop_index(op.f("ix_qnrs_is_archived"), table_name="qnrs")
    op.drop_table("qnrs")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
