"""add_creator_profile_and_credential_fields

Revision ID: aa7ad52a8902
Revises: 6241ae1d0aed
Create Date: 2026-02-12 13:44:36.868506

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aa7ad52a8902"
down_revision: Union[str, None] = "6241ae1d0aed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Sprint 6: Creator profile, credential, and economics-aware QNR metadata
    op.add_column("qnrs", sa.Column("intended_audience", sa.String(length=200), nullable=True))
    op.add_column("qnrs", sa.Column("use_case", sa.String(length=200), nullable=True))
    op.add_column(
        "qnrs",
        sa.Column(
            "quality_review_status",
            sa.String(length=30),
            server_default="unreviewed",
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_qnrs_quality_review_status"), "qnrs", ["quality_review_status"], unique=False
    )
    op.add_column("users", sa.Column("bio", sa.Text(), nullable=True))
    op.add_column("users", sa.Column("website_url", sa.String(length=500), nullable=True))
    op.add_column("users", sa.Column("linkedin_url", sa.String(length=500), nullable=True))
    op.add_column(
        "users",
        sa.Column(
            "credential_level", sa.String(length=30), server_default="unverified", nullable=False
        ),
    )
    op.add_column("users", sa.Column("credential_details", sa.String(length=500), nullable=True))
    op.add_column(
        "users",
        sa.Column(
            "show_credential_details", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.add_column("users", sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("users", sa.Column("governance_role", sa.String(length=50), nullable=True))
    op.create_index(op.f("ix_users_credential_level"), "users", ["credential_level"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_credential_level"), table_name="users")
    op.drop_column("users", "governance_role")
    op.drop_column("users", "verified_at")
    op.drop_column("users", "show_credential_details")
    op.drop_column("users", "credential_details")
    op.drop_column("users", "credential_level")
    op.drop_column("users", "linkedin_url")
    op.drop_column("users", "website_url")
    op.drop_column("users", "bio")
    op.drop_index(op.f("ix_qnrs_quality_review_status"), table_name="qnrs")
    op.drop_column("qnrs", "quality_review_status")
    op.drop_column("qnrs", "use_case")
    op.drop_column("qnrs", "intended_audience")
