"""initial_decision_tree_schema

Revision ID: d8829c1bb096
Revises:
Create Date: 2026-07-23 08:50:19.080318

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "d8829c1bb096"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_deletion_failures",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("clerk_user_id", sa.String(length=255), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=False),
        sa.Column("attempt_count", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_account_deletion_failures")),
    )
    op.create_index(
        op.f("ix_account_deletion_failures_clerk_user_id"),
        "account_deletion_failures",
        ["clerk_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_account_deletion_failures_unresolved_clerk",
        "account_deletion_failures",
        ["clerk_user_id"],
        unique=False,
        postgresql_where=sa.text("resolved_at IS NULL"),
    )
    op.create_index(
        op.f("ix_account_deletion_failures_user_id"),
        "account_deletion_failures",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("clerk_user_id", sa.String(length=255), nullable=True),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("website_url", sa.String(length=500), nullable=True),
        sa.Column("linkedin_url", sa.String(length=500), nullable=True),
        sa.Column(
            "credential_level", sa.String(length=30), server_default="unverified", nullable=False
        ),
        sa.Column("credential_details", sa.String(length=500), nullable=True),
        sa.Column(
            "show_credential_details", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "creator_page_public", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("governance_role", sa.String(length=50), nullable=True),
        sa.Column("stripe_customer_id", sa.String(length=255), nullable=True),
        sa.Column("stripe_subscription_id", sa.String(length=255), nullable=True),
        sa.Column("subscription_status", sa.String(length=30), nullable=True),
        sa.Column("subscription_period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("subscription_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_premium", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "subscription_cancel_at_period_end",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "cancellation_explainer_pending",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "cancellation_explainer_acknowledged_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "workflow_pick_required", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("live_workflow_root_id", sa.Uuid(), nullable=True),
        sa.Column("free_usage_epoch", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_index(op.f("ix_users_clerk_user_id"), "users", ["clerk_user_id"], unique=True)
    op.create_index(op.f("ix_users_credential_level"), "users", ["credential_level"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "decision_trees",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("graph_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_public", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("was_ever_public", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("parent_decision_tree_id", sa.Uuid(), nullable=True),
        sa.Column("is_current", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("is_archived", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("intended_audience", sa.String(length=200), nullable=True),
        sa.Column("use_case", sa.String(length=200), nullable=True),
        sa.Column(
            "quality_review_status",
            sa.String(length=30),
            server_default="unreviewed",
            nullable=False,
        ),
        sa.Column("reasoning_status", sa.String(length=20), nullable=True),
        sa.Column(
            "mcp_discoverable", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("billing_dormant", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("cevi_legal", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["parent_decision_tree_id"],
            ["decision_trees.id"],
            name=op.f("fk_decision_trees_parent_decision_tree_id_decision_trees"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_decision_trees")),
    )
    op.create_index(
        op.f("ix_decision_trees_billing_dormant"),
        "decision_trees",
        ["billing_dormant"],
        unique=False,
    )
    op.create_index(
        op.f("ix_decision_trees_is_archived"), "decision_trees", ["is_archived"], unique=False
    )
    op.create_index(
        op.f("ix_decision_trees_is_current"), "decision_trees", ["is_current"], unique=False
    )
    op.create_index(
        op.f("ix_decision_trees_is_public"), "decision_trees", ["is_public"], unique=False
    )
    op.create_index(
        op.f("ix_decision_trees_mcp_discoverable"),
        "decision_trees",
        ["mcp_discoverable"],
        unique=False,
    )
    op.create_index(
        op.f("ix_decision_trees_quality_review_status"),
        "decision_trees",
        ["quality_review_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_decision_trees_reasoning_status"),
        "decision_trees",
        ["reasoning_status"],
        unique=False,
    )
    op.create_index(op.f("ix_decision_trees_title"), "decision_trees", ["title"], unique=False)
    op.create_index(
        op.f("ix_decision_trees_was_ever_public"),
        "decision_trees",
        ["was_ever_public"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_decision_trees_author_id_users"), "decision_trees", "users", ["author_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_users_live_workflow_root_id_decision_trees"),
        "users",
        "decision_trees",
        ["live_workflow_root_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_check_constraint(
        "ck_decision_trees_reasoning_status_valid",
        "decision_trees",
        "reasoning_status IS NULL OR reasoning_status IN ('pending','compiled','failed')",
    )
    op.create_table(
        "decision_tree_lexicon_drafts",
        sa.Column("decision_tree_id", sa.Uuid(), nullable=False),
        sa.Column(
            "body_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("lexicon_hash", sa.String(length=64), nullable=True),
        sa.Column("graph_hash_at_save", sa.String(length=64), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["decision_tree_id"],
            ["decision_trees.id"],
            name=op.f("fk_decision_tree_lexicon_drafts_decision_tree_id_decision_trees"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("decision_tree_id", name=op.f("pk_decision_tree_lexicon_drafts")),
    )
    op.create_table(
        "decision_tree_research_corpora",
        sa.Column("decision_tree_id", sa.Uuid(), nullable=False),
        sa.Column("body_text", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["decision_tree_id"],
            ["decision_trees.id"],
            name=op.f("fk_decision_tree_research_corpora_decision_tree_id_decision_trees"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("decision_tree_id", name=op.f("pk_decision_tree_research_corpora")),
    )
    op.create_table(
        "decision_tree_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("decision_tree_id", sa.Uuid(), nullable=False),
        sa.Column("current_node_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("user_responses", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("conclusion_reached", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["decision_tree_id"],
            ["decision_trees.id"],
            name=op.f("fk_decision_tree_sessions_decision_tree_id_decision_trees"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_decision_tree_sessions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_decision_tree_sessions")),
    )
    op.create_index(
        op.f("ix_decision_tree_sessions_decision_tree_id"),
        "decision_tree_sessions",
        ["decision_tree_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_decision_tree_sessions_user_id"),
        "decision_tree_sessions",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "in_progress_decision_tree_generations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "langgraph_thread_id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False
        ),
        sa.Column(
            "user_prompt_preview", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_checkpoint_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("graph_version", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column(
            "workflow_version",
            sqlmodel.sql.sqltypes.AutoString(length=50),
            server_default=sa.text("'1.0.0'"),
            nullable=False,
        ),
        sa.Column("workflow_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_phase", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_in_progress_decision_tree_generations_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_in_progress_decision_tree_generations")),
    )
    op.create_index(
        "idx_cleanup_candidates",
        "in_progress_decision_tree_generations",
        ["expires_at", "last_checkpoint_at"],
        unique=False,
    )
    op.create_index(
        "idx_user_active_generations",
        "in_progress_decision_tree_generations",
        ["user_id", "expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_in_progress_decision_tree_generations_expires_at"),
        "in_progress_decision_tree_generations",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_in_progress_decision_tree_generations_langgraph_thread_id"),
        "in_progress_decision_tree_generations",
        ["langgraph_thread_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_in_progress_decision_tree_generations_last_checkpoint_at"),
        "in_progress_decision_tree_generations",
        ["last_checkpoint_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_in_progress_decision_tree_generations_user_id"),
        "in_progress_decision_tree_generations",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "mcp_tool_invocations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("tool_name", sa.String(length=80), nullable=False),
        sa.Column("outcome", sa.String(length=64), nullable=False),
        sa.Column("decision_tree_id", sa.Uuid(), nullable=True),
        sa.Column("oauth_client_id", sa.String(length=255), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("reasoning_ms", sa.Integer(), nullable=True),
        sa.Column("question_count", sa.Integer(), nullable=True),
        sa.Column("edge_count", sa.Integer(), nullable=True),
        sa.Column("answered_count", sa.Integer(), nullable=True),
        sa.Column("sat_calls", sa.Integer(), nullable=True),
        sa.Column("quota_weight", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("estimated_cost_usd_micros", sa.Integer(), nullable=True),
        sa.Column(
            "cost_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_mcp_tool_invocations_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mcp_tool_invocations")),
    )
    op.create_index(
        "ix_mcp_tool_invocations_created_at", "mcp_tool_invocations", ["created_at"], unique=False
    )
    op.create_index(
        "ix_mcp_tool_invocations_tool_outcome",
        "mcp_tool_invocations",
        ["tool_name", "outcome"],
        unique=False,
    )
    op.create_index(
        "ix_mcp_tool_invocations_user_created",
        "mcp_tool_invocations",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mcp_tool_invocations_user_id"), "mcp_tool_invocations", ["user_id"], unique=False
    )
    op.create_table(
        "reasoning_compiled_artifacts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("decision_tree_id", sa.Uuid(), nullable=False),
        sa.Column("ir_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("graph_hash", sa.String(length=64), nullable=False),
        sa.Column("compiler_version", sa.String(length=20), nullable=False),
        sa.Column("ir_format_version", sa.Integer(), nullable=False),
        sa.Column("cevi_contract_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("cevi_contract_hash", sa.String(length=64), nullable=True),
        sa.Column("research_corpus_hash", sa.String(length=64), nullable=True),
        sa.Column("cevi_legal_validation_status", sa.String(length=20), nullable=False),
        sa.Column("cevi_legal_validation_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cevi_legal_validation_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cevi_legal_validation_error", sa.Text(), nullable=True),
        sa.Column(
            "compiled_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["decision_tree_id"],
            ["decision_trees.id"],
            name=op.f("fk_reasoning_compiled_artifacts_decision_tree_id_decision_trees"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reasoning_compiled_artifacts")),
    )
    op.create_index(
        op.f("ix_reasoning_compiled_artifacts_decision_tree_id"),
        "reasoning_compiled_artifacts",
        ["decision_tree_id"],
        unique=True,
    )
    op.create_table(
        "user_audit_log",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("actor", sa.String(length=50), nullable=False),
        sa.Column("reason", sa.String(length=100), nullable=False),
        sa.Column(
            "event_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_audit_log_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_audit_log")),
    )
    op.create_index(
        op.f("ix_user_audit_log_event_type"), "user_audit_log", ["event_type"], unique=False
    )
    op.create_index(op.f("ix_user_audit_log_user_id"), "user_audit_log", ["user_id"], unique=False)
    op.create_table(
        "wizard_generation_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("thread_id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
        sa.Column("generation_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("phase", sa.String(length=20), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column(
            "event_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_wizard_generation_events_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wizard_generation_events")),
    )
    op.create_index(
        "ix_wizard_generation_events_created_at",
        "wizard_generation_events",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "ix_wizard_generation_events_event_phase",
        "wizard_generation_events",
        ["event_type", "phase"],
        unique=False,
    )
    op.create_index(
        "ix_wizard_generation_events_thread_id",
        "wizard_generation_events",
        ["thread_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wizard_generation_events_user_id"),
        "wizard_generation_events",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "memos",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("recommendations", sa.Text(), nullable=False),
        sa.Column(
            "llm_response",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["decision_tree_sessions.id"],
            name=op.f("fk_memos_session_id_decision_tree_sessions"),
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_memos_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memos")),
    )
    op.create_index(op.f("ix_memos_session_id"), "memos", ["session_id"], unique=False)
    op.create_index(op.f("ix_memos_user_id"), "memos", ["user_id"], unique=False)
    op.create_table(
        "reasoning_evaluation_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("decision_tree_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=True),
        sa.Column("caller_user_id", sa.Uuid(), nullable=True),
        sa.Column("outcome", sa.String(length=20), nullable=False),
        sa.Column(
            "evidence_items",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("conflict_report", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("user_resolutions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "final_facts",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("permissive_mode", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("explanation", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "triggered_edges",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("minimal_repairs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "ingest_warnings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "report",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("ingest_envelope", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["caller_user_id"],
            ["users.id"],
            name=op.f("fk_reasoning_evaluation_runs_caller_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["decision_tree_id"],
            ["decision_trees.id"],
            name=op.f("fk_reasoning_evaluation_runs_decision_tree_id_decision_trees"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["decision_tree_sessions.id"],
            name=op.f("fk_reasoning_evaluation_runs_session_id_decision_tree_sessions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reasoning_evaluation_runs")),
    )
    op.create_index(
        "ix_reasoning_evaluation_runs_decision_tree_created",
        "reasoning_evaluation_runs",
        ["decision_tree_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reasoning_evaluation_runs_decision_tree_id"),
        "reasoning_evaluation_runs",
        ["decision_tree_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reasoning_evaluation_runs_outcome"),
        "reasoning_evaluation_runs",
        ["outcome"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reasoning_evaluation_runs_session_id"),
        "reasoning_evaluation_runs",
        ["session_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_reasoning_evaluation_runs_session_id"), table_name="reasoning_evaluation_runs"
    )
    op.drop_index(
        op.f("ix_reasoning_evaluation_runs_outcome"), table_name="reasoning_evaluation_runs"
    )
    op.drop_index(
        op.f("ix_reasoning_evaluation_runs_decision_tree_id"),
        table_name="reasoning_evaluation_runs",
    )
    op.drop_index(
        "ix_reasoning_evaluation_runs_decision_tree_created", table_name="reasoning_evaluation_runs"
    )
    op.drop_table("reasoning_evaluation_runs")
    op.drop_index(op.f("ix_memos_user_id"), table_name="memos")
    op.drop_index(op.f("ix_memos_session_id"), table_name="memos")
    op.drop_table("memos")
    op.drop_index(
        op.f("ix_wizard_generation_events_user_id"), table_name="wizard_generation_events"
    )
    op.drop_index("ix_wizard_generation_events_thread_id", table_name="wizard_generation_events")
    op.drop_index("ix_wizard_generation_events_event_phase", table_name="wizard_generation_events")
    op.drop_index("ix_wizard_generation_events_created_at", table_name="wizard_generation_events")
    op.drop_table("wizard_generation_events")
    op.drop_index(op.f("ix_user_audit_log_user_id"), table_name="user_audit_log")
    op.drop_index(op.f("ix_user_audit_log_event_type"), table_name="user_audit_log")
    op.drop_table("user_audit_log")
    op.drop_index(
        op.f("ix_reasoning_compiled_artifacts_decision_tree_id"),
        table_name="reasoning_compiled_artifacts",
    )
    op.drop_table("reasoning_compiled_artifacts")
    op.drop_index(op.f("ix_mcp_tool_invocations_user_id"), table_name="mcp_tool_invocations")
    op.drop_index("ix_mcp_tool_invocations_user_created", table_name="mcp_tool_invocations")
    op.drop_index("ix_mcp_tool_invocations_tool_outcome", table_name="mcp_tool_invocations")
    op.drop_index("ix_mcp_tool_invocations_created_at", table_name="mcp_tool_invocations")
    op.drop_table("mcp_tool_invocations")
    op.drop_index(
        op.f("ix_in_progress_decision_tree_generations_user_id"),
        table_name="in_progress_decision_tree_generations",
    )
    op.drop_index(
        op.f("ix_in_progress_decision_tree_generations_last_checkpoint_at"),
        table_name="in_progress_decision_tree_generations",
    )
    op.drop_index(
        op.f("ix_in_progress_decision_tree_generations_langgraph_thread_id"),
        table_name="in_progress_decision_tree_generations",
    )
    op.drop_index(
        op.f("ix_in_progress_decision_tree_generations_expires_at"),
        table_name="in_progress_decision_tree_generations",
    )
    op.drop_index("idx_user_active_generations", table_name="in_progress_decision_tree_generations")
    op.drop_index("idx_cleanup_candidates", table_name="in_progress_decision_tree_generations")
    op.drop_table("in_progress_decision_tree_generations")
    op.drop_index(op.f("ix_decision_tree_sessions_user_id"), table_name="decision_tree_sessions")
    op.drop_index(
        op.f("ix_decision_tree_sessions_decision_tree_id"), table_name="decision_tree_sessions"
    )
    op.drop_table("decision_tree_sessions")
    op.drop_table("decision_tree_research_corpora")
    op.drop_table("decision_tree_lexicon_drafts")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_credential_level"), table_name="users")
    op.drop_index(op.f("ix_users_clerk_user_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_decision_trees_was_ever_public"), table_name="decision_trees")
    op.drop_index(op.f("ix_decision_trees_title"), table_name="decision_trees")
    op.drop_index(op.f("ix_decision_trees_reasoning_status"), table_name="decision_trees")
    op.drop_index(op.f("ix_decision_trees_quality_review_status"), table_name="decision_trees")
    op.drop_index(op.f("ix_decision_trees_mcp_discoverable"), table_name="decision_trees")
    op.drop_index(op.f("ix_decision_trees_is_public"), table_name="decision_trees")
    op.drop_index(op.f("ix_decision_trees_is_current"), table_name="decision_trees")
    op.drop_index(op.f("ix_decision_trees_is_archived"), table_name="decision_trees")
    op.drop_index(op.f("ix_decision_trees_billing_dormant"), table_name="decision_trees")
    op.drop_table("decision_trees")
    op.drop_index(
        op.f("ix_account_deletion_failures_user_id"), table_name="account_deletion_failures"
    )
    op.drop_index(
        "ix_account_deletion_failures_unresolved_clerk",
        table_name="account_deletion_failures",
        postgresql_where=sa.text("resolved_at IS NULL"),
    )
    op.drop_index(
        op.f("ix_account_deletion_failures_clerk_user_id"), table_name="account_deletion_failures"
    )
    op.drop_table("account_deletion_failures")
    # ### end Alembic commands ###
