"""Add in_progress_qnr_generations table

Revision ID: feaedf1f418c
Revises: 9601d90d2008
Create Date: 2026-01-15 17:37:24.282957

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "feaedf1f418c"
down_revision: Union[str, None] = "9601d90d2008"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "in_progress_qnr_generations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "langgraph_thread_id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False
        ),
        sa.Column(
            "user_prompt_preview", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_checkpoint_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("graph_version", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("current_phase", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_in_progress_qnr_generations_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_in_progress_qnr_generations")),
    )
    op.create_index(
        "idx_cleanup_candidates",
        "in_progress_qnr_generations",
        ["expires_at", "last_checkpoint_at"],
        unique=False,
    )
    op.create_index(
        "idx_user_active_generations",
        "in_progress_qnr_generations",
        ["user_id", "expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_in_progress_qnr_generations_expires_at"),
        "in_progress_qnr_generations",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_in_progress_qnr_generations_langgraph_thread_id"),
        "in_progress_qnr_generations",
        ["langgraph_thread_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_in_progress_qnr_generations_last_checkpoint_at"),
        "in_progress_qnr_generations",
        ["last_checkpoint_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_in_progress_qnr_generations_user_id"),
        "in_progress_qnr_generations",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_in_progress_qnr_generations_user_id"), table_name="in_progress_qnr_generations"
    )
    op.drop_index(
        op.f("ix_in_progress_qnr_generations_last_checkpoint_at"),
        table_name="in_progress_qnr_generations",
    )
    op.drop_index(
        op.f("ix_in_progress_qnr_generations_langgraph_thread_id"),
        table_name="in_progress_qnr_generations",
    )
    op.drop_index(
        op.f("ix_in_progress_qnr_generations_expires_at"), table_name="in_progress_qnr_generations"
    )
    op.drop_index("idx_user_active_generations", table_name="in_progress_qnr_generations")
    op.drop_index("idx_cleanup_candidates", table_name="in_progress_qnr_generations")
    op.drop_table("in_progress_qnr_generations")
    # ### end Alembic commands ###
